2021-06-28 17:24:03,831:INFO: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) 
2021-06-28 17:24:51,743:INFO: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) 
2021-06-28 17:24:53,964:ERROR:Exception on / [GET] 
Traceback (most recent call last):
  File "c:\users\ncs\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ncs\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ncs\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ncs\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "F:\Cuelogic\Training\5 Flask\Environments\errorHandling\error_logging\app.py", line 17, in index
    return 5/0
ZeroDivisionError: division by zero
2021-06-28 17:24:53,967:INFO:127.0.0.1 - - [28/Jun/2021 17:24:53] "[35m[1mGET / HTTP/1.1[0m" 500 - 
